In [10]:
import numpy
import pandas

In [11]:
haha = pandas.read_csv('iris.csv')

In [36]:
haha[['sepal_length','sepal_width','petal_length','petal_width','species']][:30] #[['a','b']]

# haha[:]

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa

In [20]:
from sklearn import tree

In [42]:
X = haha[['sepal_length','sepal_width','petal_length','petal_width']][:]
Y = haha[['species']][:]
# clf = tree.DecisionTreeClassifier()
# clf = clf.fit(X, Y)
# X,Y

In [43]:
# import pickle
# # now you can save it to a file
# with open('test.pkl', 'wb') as f:
#     pickle.dump(clf, f)

In [44]:
# clf.predict(haha[['sepal_length','sepal_width','petal_length','petal_width']][30:])

In [45]:
import numpy as np
from sklearn.model_selection import train_test_split
# X, Y = np.arange(10).reshape((5, 2)), range(5)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [46]:
X_train, X_test, y_train, y_test

(     sepal_length  sepal_width  petal_length  petal_width
 22            4.6          3.6           1.0          0.2
 15            5.7          4.4           1.5          0.4
 65            6.7          3.1           4.4          1.4
 11            4.8          3.4           1.6          0.2
 42            4.4          3.2           1.3          0.2
 146           6.3          2.5           5.0          1.9
 51            6.4          3.2           4.5          1.5
 27            5.2          3.5           1.5          0.2
 4             5.0          3.6           1.4          0.2
 32            5.2          4.1           1.5          0.1
 142           5.8          2.7           5.1          1.9
 85            6.0          3.4           4.5          1.6
 86            6.7          3.1           4.7          1.5
 16            5.4          3.9           1.3          0.4
 10            5.4          3.7           1.5          0.2
 81            5.5          2.4           3.7          1.0
 133           6.3          2.8           5.1          1.5
 137           6.4          3.1           5.5          1.8
 75            6.6          3.0           4.4          1.4
 109           7.2          3.6           6.1          2.5
 96            5.7          2.9           4.2          1.3
 105           7.6          3.0           6.6          2.1
 66            5.6          3.0           4.5          1.5
 0             5.1          3.5           1.4          0.2
 122           7.7          2.8           6.7          2.0
 67            5.8          2.7           4.1          1.0
 28            5.2          3.4           1.4          0.2
 40            5.0          3.5           1.3          0.3
 44            5.1          3.8           1.9          0.4
 60            5.0          2.0           3.5          1.0
 ..            ...          ...           ...          ...
 91            6.1          3.0           4.6          1.4
 41            4.5          2.3           1.3          0.3
 58            6.6          2.9           4.6          1.3
 90            5.5          2.6           4.4          1.2
 48            5.3          3.7           1.5          0.2
 88            5.6          3.0           4.1          1.3
 107           7.3          2.9           6.3          1.8
 124           6.7          3.3           5.7          2.1
 21            5.1          3.7           1.5          0.4
 57            4.9          2.4           3.3          1.0
 144           6.7          3.3           5.7          2.5
 129           7.2          3.0           5.8          1.6
 37            4.9          3.1           1.5          0.1
 140           6.7          3.1           5.6          2.4
 1             4.9          3.0           1.4          0.2
 52            6.9          3.1           4.9          1.5
 130           7.4          2.8           6.1          1.9
 103           6.3          2.9           5.6          1.8
 99            5.7          2.8           4.1          1.3
 116           6.5          3.0           5.5          1.8
 87            6.3          2.3           4.4          1.3
 74            6.4          2.9           4.3          1.3
 121           5.6          2.8           4.9          2.0
 149           5.9          3.0           5.1          1.8
 20            5.4          3.4           1.7          0.2
 71            6.1          2.8           4.0          1.3
 106           4.9          2.5           4.5          1.7
 14            5.8          4.0           1.2          0.2
 92            5.8          2.6           4.0          1.2
 102           7.1          3.0           5.9          2.1

 [120 rows x 4 columns],
      sepal_length  sepal_width  petal_length  petal_width
 73            6.1          2.8           4.7          1.2
 18            5.7          3.8           1.7          0.3
 118           7.7          2.6           6.9          2.3
 78            6.0          2.9           4.5          1.5
 76            6.8          2.8           4.8          1.4
 31            5.4          3.4           1.5          0.4
 64            5.6          2.9           3.6          1.3
 141           6.9          3.1           5.1          2.3
 68            6.2          2.2           4.5          1.5
 82            5.8          2.7           3.9          1.2
 110           6.5          3.2           5.1          2.0
 12            4.8          3.0           1.4          0.1
 36            5.5          3.5           1.3          0.2
 9             4.9          3.1           1.5          0.1
 19            5.1          3.8           1.5          0.3
 56            6.3          3.3           4.7          1.6
 104           6.5          3.0           5.8          2.2
 69            5.6          2.5           3.9          1.1
 55            5.7          2.8           4.5          1.3
 132           6.4          2.8           5.6          2.2
 29            4.7          3.2           1.6          0.2
 127           6.1          3.0           4.9          1.8
 26            5.0          3.4           1.6          0.4
 128           6.4          2.8           5.6          2.1
 131           7.9          3.8           6.4          2.0
 145           6.7          3.0           5.2          2.3
 108           6.7          2.5           5.8          1.8
 143           6.8          3.2           5.9          2.3
 45            4.8          3.0           1.4          0.3
 30            4.8          3.1           1.6          0.2,
         species
 22       setosa
 15       setosa
 65   versicolor
 11       setosa
 42       setosa
 146   virginica
 51   versicolor
 27       setosa
 4        setosa
 32       setosa
 142   virginica
 85   versicolor
 86   versicolor
 16       setosa
 10       setosa
 81   versicolor
 133   virginica
 137   virginica
 75   versicolor
 109   virginica
 96   versicolor
 105   virginica
 66   versicolor
 0        setosa
 122   virginica
 67   versicolor
 28       setosa
 40       setosa
 44       setosa
 60   versicolor
 ..          ...
 91   versicolor
 41       setosa
 58   versicolor
 90   versicolor
 48       setosa
 88   versicolor
 107   virginica
 124   virginica
 21       setosa
 57   versicolor
 144   virginica
 129   virginica
 37       setosa
 140   virginica
 1        setosa
 52   versicolor
 130   virginica
 103   virginica
 99   versicolor
 116   virginica
 87   versicolor
 74   versicolor
 121   virginica
 149   virginica
 20       setosa
 71   versicolor
 106   virginica
 14       setosa
 92   versicolor
 102   virginica

 [120 rows x 1 columns],
         species
 73   versicolor
 18       setosa
 118   virginica
 78   versicolor
 76   versicolor
 31       setosa
 64   versicolor
 141   virginica
 68   versicolor
 82   versicolor
 110   virginica
 12       setosa
 36       setosa
 9        setosa
 19       setosa
 56   versicolor
 104   virginica
 69   versicolor
 55   versicolor
 132   virginica
 29       setosa
 127   virginica
 26       setosa
 128   virginica
 131   virginica
 145   virginica
 108   virginica
 143   virginica
 45       setosa
 30       setosa)

In [47]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
# X,Y

In [67]:
# lol = pandas.DataFrame(clf.predict(X_test))
# lol = lol.append(y_train[0])
lol = clf.predict(X_test)
y_test['prediction'] = lol
y_test

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

        species  prediction
73   versicolor  versicolor
18       setosa      setosa
118   virginica   virginica
78   versicolor  versicolor
76   versicolor  versicolor
31       setosa      setosa
64   versicolor  versicolor
141   virginica   virginica
68   versicolor  versicolor
82   versicolor  versicolor
110   virginica   virginica
12       setosa      setosa
36       setosa      setosa
9        setosa      setosa
19       setosa      setosa
56   versicolor  versicolor
104   virginica   virginica
69   versicolor  versicolor
55   versicolor  versicolor
132   virginica   virginica
29       setosa      setosa
127   virginica   virginica
26       setosa      setosa
128   virginica   virginica
131   virginica   virginica
145   virginica   virginica
108   virginica   virginica
143   virginica   virginica
45       setosa      setosa
30       setosa      setosa

In [56]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test['spec'], pred)

              0     species
0    versicolor         NaN
1        setosa         NaN
2     virginica         NaN
3    versicolor         NaN
4    versicolor         NaN
5        setosa         NaN
6    versicolor         NaN
7     virginica         NaN
8    versicolor         NaN
9    versicolor         NaN
10    virginica         NaN
11       setosa         NaN
12       setosa         NaN
13       setosa         NaN
14       setosa         NaN
15   versicolor         NaN
16    virginica         NaN
17   versicolor         NaN
18   versicolor         NaN
19    virginica         NaN
20       setosa         NaN
21    virginica         NaN
22       setosa         NaN
23    virginica         NaN
24    virginica         NaN
25    virginica         NaN
26    virginica         NaN
27    virginica         NaN
28       setosa         NaN
29       setosa         NaN
..          ...         ...
91          NaN  versicolor
41          NaN      setosa
58          NaN  versicolor
90          NaN  versicolor
48          NaN      setosa
88          NaN  versicolor
107         NaN   virginica
124         NaN   virginica
21          NaN      setosa
57          NaN  versicolor
144         NaN   virginica
129         NaN   virginica
37          NaN      setosa
140         NaN   virginica
1           NaN      setosa
52          NaN  versicolor
130         NaN   virginica
103         NaN   virginica
99          NaN  versicolor
116         NaN   virginica
87          NaN  versicolor
74          NaN  versicolor
121         NaN   virginica
149         NaN   virginica
20          NaN      setosa
71          NaN  versicolor
106         NaN   virginica
14          NaN      setosa
92          NaN  versicolor
102         NaN   virginica

[150 rows x 2 columns]